### PR TITLE
Contribution form for ai-minimization-toolkit.

### PR DESCRIPTION
**Pull request by abigailgold**
This tool is aimed at helping machine learning model developers to adhere to the data minimization principle by determining the minimal level of detail required for newly collected data to make accurate predictions with the model.

### CODE REVIEW

**Comment by kboeckl** [comment]
Hi @abigailgold. Thank you for your contribution, and my sincerest apologies for such a delayed response to your pull request. I'm now reviewing this, and will reach out soon with any follow up questions or comments.

**Review by kboeckl — COMMENTED** [review]
Hi @abigailgold - thanks again for contributing. This looks great. I just have one comment before approving and merging this contribution. When looking over the AI Minimization Toolkit, I thought this tool might also appropriately map to the Privacy Framework Category of Disassociated Processing (CT.DP-P), which provides various outcomes and capabilities for privacy-protective data management -- including different ways to achieve the principle of data minimization. If you agree that this make sense as a mapping for your contribution, the tool can be mapped to two different Categories (i.e., CT.DP-P and PR.PT-P). You can simply add it with another commit. If not, that would also be fine, and I can approve your resource as-is and get it added it to the repository. Please let me know what you think.

**Comment by abigailgold** [comment]
@kboeckl Thanks for the suggestion, I added it to the list.

**Review by kboeckl — APPROVED** [review]
Great, I'll merge this in and let you know once this is added to our website. Thank you, again, for contributing!

**Comment by kboeckl** [comment]
The contribution is now live at the following webpage: [https://www.nist.gov/privacy-framework/resource-repository/browse/guidance-and-tools/ai-minimization-toolkit](https://www.nist.gov/privacy-framework/resource-repository/browse/guidance-and-tools/ai-minimization-toolkit)

**Pull request merged**
